// SKELETON: Gemini assistant sheet for the LG agentic Flutter starter kit.
//
// This widget only exposes a UI hook.
// All LLM execution, voice processing and safety handling
// must be performed by Antigravity + Gemini agent workflows.

import 'package:flutter/material.dart';

class GeminiChatSheet extends StatefulWidget {
  const GeminiChatSheet({super.key});

  @override
  State<GeminiChatSheet> createState() => _GeminiChatSheetState();
}

class _GeminiChatSheetState extends State<GeminiChatSheet> {
  final TextEditingController controller = TextEditingController();

  bool processing = false;
  String? response;

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  /// SKELETON HOOK
  ///
  /// Agent workflows will:
  /// - interpret the user intent
  /// - generate agent plans
  /// - trigger workflows (API → KML → LG)
  /// - optionally return a textual explanation
  Future<void> runAssistantWorkflow() async {
    final prompt = controller.text.trim();
    if (prompt.isEmpty) return;

    setState(() {
      processing = true;
      response = null;
    });

    // SKELETON:
    // The assistant pipeline must be generated by Antigravity agents.

    await Future.delayed(const Duration(milliseconds: 600));

    if (!mounted) return;

    setState(() {
      processing = false;
      response =
          'Starter kit skeleton – Gemini assistant workflow not bound yet.';
    });
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.only(
        bottom: MediaQuery.of(context).viewInsets.bottom,
        left: 16,
        right: 16,
        top: 16,
      ),
      child: SafeArea(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Text(
              "Gemini Agent Assistant",
              style: TextStyle(
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 12),

            TextField(
              controller: controller,
              maxLines: 3,
              decoration: const InputDecoration(
                hintText: "Describe your task for the agent workflow…",
              ),
            ),

            const SizedBox(height: 12),

            SizedBox(
              width: double.infinity,
              child: ElevatedButton(
                onPressed: processing ? null : runAssistantWorkflow,
                child: processing
                    ? const SizedBox(
                        width: 18,
                        height: 18,
                        child: CircularProgressIndicator(strokeWidth: 2),
                      )
                    : const Text("Run assistant"),
              ),
            ),

            const SizedBox(height: 12),

            if (response != null)
              Text(
                response!,
                style: const TextStyle(fontSize: 14),
              ),

            const SizedBox(height: 8),
          ],
        ),
      ),
    );
  }
}
