// SKELETON: Geocoding API contract for the LG agentic Flutter starter kit.
// Real HTTP clients and providers must be generated by Antigravity agents.

/// Simple geographic coordinate model used across workflows.
class LatLng {
  final double lat;
  final double lng;

  const LatLng(this.lat, this.lng);
}

/// Contract for a geocoding data source.
///
/// Implementations are generated by agent workflows
/// (for example using public open APIs).
abstract class GeocodingApi {
  /// Returns coordinates for a textual place query.
  ///
  /// SKELETON HOOK:
  /// - HTTP client
  /// - endpoint selection
  /// - error handling
  /// must be generated by agents.
  Future<LatLng> getCoordinates(String place);
}
