import 'package:flutter/material.dart';

import '../api/geocoding_api.dart';
import '../lg/dummy_lg_kml_sender.dart';
import 'geocoding_screen.dart';

/// Temporary demo entry screen for the starter kit.
/// Real dependency injection is generated by agent workflows.
class DemoEntryScreen
    extends
        StatelessWidget {
  final GeocodingApi geocodingApi;

  const DemoEntryScreen({
    super.key,
    required this.geocodingApi,
  });

  @override
  Widget build(
    BuildContext context,
  ) {
    return GeocodingDemoScreen(
      geocodingApi: geocodingApi,
      lgSender: DummyLgKmlSender(),
    );
  }
}
