import '../../kmls/common_kml.dart';

/// Contract for sending KML payloads to the Liquid Galaxy rig.
/// Implementations are generated by agent workflows.
abstract class LgKmlSender {
  Future<
    void
  >
  send(
    KmlPayload payload,
  );
}
