// SKELETON: Home screen for the LG agentic Flutter starter kit.
// This screen demonstrates the UI entry point and workflow hooks only.
// All real logic (API, KML generation, LG communication) must be injected
// by Antigravity + Gemini agents.

import 'package:flutter/material.dart';

import '../../widgets/gradient_background.dart';
import '../assistant/gemini_assistant_button.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  final TextEditingController placeController = TextEditingController();

  bool loading = false;
  String? infoMessage;

  @override
  void dispose() {
    placeController.dispose();
    super.dispose();
  }

  /// SKELETON HOOK
  ///
  /// This method is intentionally empty.
  /// Agent workflows will inject:
  /// - API calls
  /// - KML generation
  /// - Liquid Galaxy communication
  Future<void> runAgentWorkflow() async {
    setState(() {
      loading = true;
      infoMessage = null;
    });

    // SKELETON:
    // The following steps must be generated by agents:
    //
    // 1. Read user input
    // 2. Call external API (lib/api)
    // 3. Convert response to KML (lib/data/kmls)
    // 4. Validate KML
    // 5. Send KML to Liquid Galaxy (lib/lg)
    // 6. Fly camera / update view

    await Future.delayed(const Duration(milliseconds: 600));

    if (!mounted) return;

    setState(() {
      loading = false;
      infoMessage =
          'Starter kit skeleton – no workflow bound yet. Run an agent workflow.';
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: const GeminiAssistantButton(),

      body: GradientBackground(
        child: DefaultTextStyle.merge(
          style: const TextStyle(decoration: TextDecoration.none),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const SizedBox(height: 60),

              Padding(
                padding: const EdgeInsets.only(
                  left: 20,
                  right: 20,
                  top: 20,
                ),
                child: Row(
                  children: const [
                    Expanded(
                      child: Text(
                        "Liquid Galaxy Flutter Starter Kit",
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                        style: TextStyle(
                          fontSize: 28,
                          fontWeight: FontWeight.bold,
                          color: Colors.white,
                        ),
                      ),
                    ),
                  ],
                ),
              ),

              const SizedBox(height: 10),

              const Padding(
                padding: EdgeInsets.symmetric(horizontal: 20),
                child: Text(
                  "Agentic workflow entry screen",
                  style: TextStyle(
                    fontSize: 14,
                    color: Colors.white70,
                  ),
                ),
              ),

              const SizedBox(height: 24),

              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 20),
                child: Row(
                  children: [
                    Expanded(
                      child: TextField(
                        controller: placeController,
                        style: const TextStyle(color: Colors.white),
                        decoration: const InputDecoration(
                          hintText:
                              "Enter a place or dataset query (workflow input)",
                          hintStyle: TextStyle(color: Colors.white54),
                          enabledBorder: UnderlineInputBorder(
                            borderSide: BorderSide(color: Colors.white24),
                          ),
                          focusedBorder: UnderlineInputBorder(
                            borderSide: BorderSide(color: Colors.white),
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(width: 10),
                    ElevatedButton(
                      onPressed: loading ? null : runAgentWorkflow,
                      child: loading
                          ? const SizedBox(
                              height: 18,
                              width: 18,
                              child: CircularProgressIndicator(
                                strokeWidth: 2,
                              ),
                            )
                          : const Text("Run"),
                    ),
                  ],
                ),
              ),

              if (infoMessage != null)
                Padding(
                  padding: const EdgeInsets.only(
                    top: 12,
                    left: 20,
                    right: 20,
                  ),
                  child: Text(
                    infoMessage!,
                    style: const TextStyle(
                      color: Colors.white70,
                    ),
                  ),
                ),

              const SizedBox(height: 24),

              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 20),
                child: Container(
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    color: Colors.white10,
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: const Text(
                    "SKELETON AREA\n\n"
                    "Agent-generated UI components, actions panels and "
                    "Liquid Galaxy controls will be injected here by "
                    "workflow steps.",
                    style: TextStyle(
                      color: Colors.white70,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
