// SKELETON: Common KML data contracts for the LG agentic Flutter starter kit.
//
// This file defines only data structures.
// All KML generation and validation logic must live in
// builder and validator files generated by agent workflows.

class KmlPayload {
  /// Full KML document (including root <kml> element).
  final String kml;

  /// Camera target latitude.
  final double latitude;

  /// Camera target longitude.
  final double longitude;

  /// Camera range (zoom / distance).
  final double range;

  const KmlPayload({
    required this.kml,
    required this.latitude,
    required this.longitude,
    required this.range,
  });
}
