// SKELETON: Flutter + Liquid Galaxy starter kit entrypoint
// This file is intentionally minimal.
// All real initialization must be generated by Antigravity agents.

import 'package:flutter/material.dart';

import 'presentation/splash/splash_screen.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // SKELETON HOOK:
  // Environment loading, secrets, and platform initialization
  // must be injected by agent workflows.
  //
  // Example (to be generated by agents):
  // - dotenv loading
  // - LG connection bootstrap
  // - API client bootstrap

  runApp(const LGStarterKitApp());
}

/// Root application widget for the LG Flutter starter kit.
///
/// SKELETON:
/// - Routing
/// - theming
/// - dependency injection
/// will be extended by agent workflows.
class LGStarterKitApp extends StatelessWidget {
  const LGStarterKitApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'LG Agentic Flutter Starter Kit',
      debugShowCheckedModeBanner: false,

      // SKELETON THEME
      // Can be safely replaced by agents when generating an app.
      theme: ThemeData.dark(),

      // SKELETON ENTRY SCREEN
      // The splash screen is used only as a visual anchor.
      home: const StartScreen(),
    );
  }
}
