// SKELETON: Flutter + Liquid Galaxy starter kit entrypoint
// This file is intentionally minimal.
// All real initialization must be generated by Antigravity agents.

import 'package:flutter/material.dart';

import 'api/geocoding_api.dart';
import 'api/dummy_geocoding_api.dart';
import 'presentation/demo_entry_screen.dart';

Future<
  void
>
main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // SKELETON HOOK:
  // Environment loading, secrets, and platform initialization
  // must be injected by agent workflows.

  final GeocodingApi geocodingApi = DummyGeocodingApi();

  runApp(
    LGStarterKitApp(
      geocodingApi: geocodingApi,
    ),
  );
}

/// Root application widget for the LG Flutter starter kit.
class LGStarterKitApp
    extends
        StatelessWidget {
  final GeocodingApi geocodingApi;

  const LGStarterKitApp({
    super.key,
    required this.geocodingApi,
  });

  @override
  Widget build(
    BuildContext context,
  ) {
    return MaterialApp(
      title: 'LG Agentic Flutter Starter Kit',
      debugShowCheckedModeBanner: false,
      theme: ThemeData.dark(),

      home: DemoEntryScreen(
        geocodingApi: geocodingApi,
      ),
    );
  }
}
