// SKELETON: Liquid Galaxy connection screen.
// This screen only collects connection parameters and exposes
// agent workflow hooks. It does not perform any real connection.

import 'package:flutter/material.dart';

import '../../widgets/gradient_background.dart';

class ConnectionScreen extends StatefulWidget {
  const ConnectionScreen({super.key});

  @override
  State<ConnectionScreen> createState() => _ConnectionScreenState();
}

class _ConnectionScreenState extends State<ConnectionScreen> {
  final TextEditingController ipController = TextEditingController();
  final TextEditingController userController = TextEditingController();
  final TextEditingController passController = TextEditingController();
  final TextEditingController portController =
      TextEditingController(text: '22');

  bool isProcessing = false;
  String statusText = 'No workflow executed';

  @override
  void dispose() {
    ipController.dispose();
    userController.dispose();
    passController.dispose();
    portController.dispose();
    super.dispose();
  }

  /// SKELETON HOOK
  ///
  /// Agent workflows will inject:
  /// - secure credential handling
  /// - LG connection validation
  /// - remote handshake logic
  Future<void> runConnectionWorkflow() async {
    setState(() {
      isProcessing = true;
      statusText = 'Running agent workflow...';
    });

    // SKELETON:
    // The following must be generated by agents:
    // - validate fields
    // - create LG connection config
    // - test connectivity
    // - persist connection profile (optional)

    await Future.delayed(const Duration(milliseconds: 700));

    if (!mounted) return;

    setState(() {
      isProcessing = false;
      statusText =
          'Starter kit skeleton – no LG connection workflow bound yet.';
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Liquid Galaxy Connection'),
        backgroundColor: Colors.transparent,
        elevation: 0,
      ),
      body: GradientBackground(
        child: SafeArea(
          child: _ConnectionBody(state: this),
        ),
      ),
    );
  }
}

class _ConnectionBody extends StatelessWidget {
  final _ConnectionScreenState state;

  const _ConnectionBody({
    required this.state,
  });

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(24),
      child: SingleChildScrollView(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const SizedBox(height: 20),

            const Text(
              'Liquid Galaxy Connection',
              style: TextStyle(
                fontSize: 28,
                fontWeight: FontWeight.bold,
                color: Colors.white,
              ),
            ),

            const SizedBox(height: 12),

            const Text(
              'Connection workflow input (agent driven)',
              style: TextStyle(
                fontSize: 14,
                color: Colors.white70,
              ),
            ),

            const SizedBox(height: 40),

            _InputField(
              controller: state.ipController,
              label: 'IP Address',
            ),
            _InputField(
              controller: state.userController,
              label: 'Username',
            ),
            _InputField(
              controller: state.passController,
              label: 'Password',
              obscure: true,
            ),
            _InputField(
              controller: state.portController,
              label: 'SSH Port',
              keyboard: TextInputType.number,
            ),

            const SizedBox(height: 30),

            SizedBox(
              width: double.infinity,
              child: ElevatedButton(
                onPressed:
                    state.isProcessing ? null : state.runConnectionWorkflow,
                child: state.isProcessing
                    ? const SizedBox(
                        height: 20,
                        width: 20,
                        child: CircularProgressIndicator(strokeWidth: 2),
                      )
                    : const Text('Run workflow'),
              ),
            ),

            const SizedBox(height: 20),

            Text(
              state.statusText,
              style: const TextStyle(
                color: Colors.white70,
                fontWeight: FontWeight.bold,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _InputField extends StatelessWidget {
  final TextEditingController controller;
  final String label;
  final bool obscure;
  final TextInputType keyboard;

  const _InputField({
    required this.controller,
    required this.label,
    this.obscure = false,
    this.keyboard = TextInputType.text,
  });

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 16),
      child: TextField(
        controller: controller,
        obscureText: obscure,
        keyboardType: keyboard,
        style: const TextStyle(color: Colors.white),
        decoration: InputDecoration(
          labelText: label,
          labelStyle: const TextStyle(color: Colors.white70),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: const BorderSide(color: Colors.white24),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: const BorderSide(color: Colors.white),
          ),
        ),
      ),
    );
  }
}
